# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('block_size', models.PositiveIntegerField()),
                ('block_height', models.PositiveIntegerField()),
                ('merkleroot', models.CharField(max_length=64)),
                ('time', models.PositiveIntegerField()),
                ('median_time', models.PositiveIntegerField()),
                ('bits', models.BigIntegerField()),
                ('nonce', models.BigIntegerField()),
                ('prev_block_hash', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talk.Block')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=1000)),
                ('block_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.Block')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('tx_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('block_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.Block')),
            ],
        ),
        migrations.CreateModel(
            name='TxIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_index', models.IntegerField(null=True)),
                ('prev_tx', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_transaction_set', to='talk.Transaction')),
                ('tx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='TxOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_index', models.IntegerField()),
                ('value', models.BigIntegerField()),
                ('tx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talk.Transaction')),
            ],
        ),
    ]
